### ISSUE TITLE
Device 'Toshiba::TMPA900CMXBG' is not supported by Toolchain !

### ISSUE THREAD

**Issue by qianfan-Zhao** [OpenNuvoton/NUC970_NuWriter#2]
Hi:
I am trying cross compile the nuwrite firmware on my  computer but keil report that TMPA900 is not supported.

I can't know which DFP should installed first. (http://www.keil.com/dd2/Pack/), could you give me some suggestions?

(I had installed Legacy support for Arm7, Arm9 & Cortex-R devices from http://www2.keil.com/mdk5/legacy)

Thanks

**Comment by yachen** [comment]
That's exactly what we did. Install Keil 5 and then the ARM7/9/Cortex-R legacy pack.
Can you show me the error window that Keil reports TMPA900 not supported? Thanks.

Sincerely,

Yi-An Chen

**Comment by qianfan-Zhao** [comment]
I don't have a license to compiling code for ARM9 deivce so mdk report this issue.

I had fixed this and can compile & run NuwriteFW, so just close this issue.
