### ISSUE TITLE
Is nuwrite support nand(size : 4GB, page : 8k, oobsize : 448)

### ISSUE THREAD

**Issue by williany** [OpenNuvoton/NUC970_NuWriter#4]
my pack image  include spl and uboot  produced by nuwrite pack.  I first erase my device(nand flash size : 4GB, page : 8k, oobsize : 448)  and then  flash it to device by pack manner, after flash, I readback the data(0~1M) from device. but I find the data on addr 0 is uboot data not spl.  Is the newest nuwrite support flash nand nand(size : 4GB, page : 8k, oobsize : 448) ? 
                                                                                                                                                                                                    thanks

**Comment by yachen** [comment]
NuWriter can support 4GB NAND flash. What's the offset of u-Boot.bin in NAND flash? NUC970 reserved block0~3 for SPL image. The block size is probably 1MB for a 4GB NAND, so your u-boot.bin and env must not occupy the first 4MB while you build the pack image.

**Comment by williany** [comment]
thanks， you are right。it's ok.
